import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";
import styles from "./index.module.css";

const Home: NextPage = () => {
  const { data } = trpc.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className={styles.title}>
        Create <span className={styles.titlePink}>T3</span> App
      </h1>

      <div className={styles.helloFrom}>
        {data ? <p>{data.greeting}</p> : <p>Loading...</p>}
      </div>
    </>
  );
};

export default Home;
